/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bmi_school;


import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class SchoolTest {
	School FCU; 

	@BeforeEach
	void setUp() throws Exception {
		FCU = new School();
		FCU.setBMILevel(24, 18);
	}

	@Test
	void testNeedExercise() {
		FCU.addStudent(new Person("001", "Nick", 1.72, 30));
		FCU.addStudent(new Person("002", "Albert", 1.7, 120));
		FCU.addStudent(new Person("003", "Jame", 1.72, 60));
		FCU.addStudent(new Person("004", "Sam", 1.72, 40));
		FCU.addStudent(new Person("005", "Peter", 1.72, 60));

		String[] tooFat = {"002"};
		assertArrayEquals(tooFat, FCU.needExercise());
	}
	
	@Test
	void testNeedEatMore() {
		FCU.addStudent(new Person("001", "Nick", 1.72, 30));
		FCU.addStudent(new Person("002", "Albert", 1.7, 120));
		FCU.addStudent(new Person("003", "Jame", 1.72, 60));
		FCU.addStudent(new Person("004", "Sam", 1.72, 40));
		FCU.addStudent(new Person("005", "Peter", 1.72, 60));

		String[] under = {"001", "004"};
		assertArrayEquals(under, FCU.needEatMore());
	}
	
	@Test
	void testFat() {
		Person p1 = new Person("001", "Nick", 1.72, 30);
		Person p2 = new Person("002", "Albert", 1.72, 120);
		Person p3 = new Person("003", "Jame", 1.72, 60);
		Person p4 = new Person("004", "Sam", 1.72, 40);
		Person p5 = new Person("005", "Peter", 1.72, 60);
		Person p6 = new Person("006", "Emily", 1.72, 120);
		
		FCU.addStudent(p1);
		FCU.addStudent(p2);
		FCU.addStudent(p3);
		FCU.addStudent(p4);
		FCU.addStudent(p5);
		FCU.addStudent(p6);

		ArrayList<Person> fat = new ArrayList<Person>();
		fat.add(p2); 
		fat.add(p6);
		assertEquals(fat, FCU.fatStudents());
	}
}
